### ISSUE TITLE
Issue converting GeoJson to PostGis - Types aren't carried across?

### ISSUE THREAD

**Issue by jpc2350** [scolab-dot-eu/pygdaltools#3] opened 2019-02-08 12:21 UTC
I have some python code that uses the pygdaltools python module to convert a geojson file to postgis.
```
    ogr = gdaltools.ogr2ogr()
    ogr.set_encoding("UTF-8")
    print("Setting Input")
    ogr.set_input(file_name, srs="EPSG:4326")

    gdaltools.Wrapper.BASEPATH = os.environ['GDAL_PATH']

    print("Setting Conn")
    conn = gdaltools.PgConnectionString(host=os.environ['DB_HOST'],
                                        port=os.environ['DB_PORT'],
                                        dbname=os.environ['DB_NAME'],
                                        user=os.environ['DB_USERNAME'],
                                        password=os.environ['DB_PASSWORD'],
                                        schema=str(self.table_prefix) + "_" + str(code))

    print("Setting Output")
    ogr.set_output(conn, table_name=table, srs="EPSG:27700")
    print("OGR Execute")
    ogr.execute()
```
The GeoJSON contains a geometry of type point

```
 "geometry": {
    "type": "Point",
    "coordinates": [
       -1.0600739160455448,
       51.53592123798526
    ]
 }
```
What I'm seeing when exporting the data from the database, is that it appears to be converted from type Point in the geojson to type Multipoint in the database.

When loading the geometry from one table into another table - with no transformation - I get the following error:

`Geometry type (MultiPoint) does not match column type (Point)`

Any Ideas as to where why ogr2ogr would be casting to Multipoint from Point?

**Comment by jpc2350** [comment] 2019-02-08 13:33
So I've delved a bit further into the ogr2ogrcmd and can see that it's defaulting to 'MULTI', but when trying to set ogr.geom_type manually - I get the following error:
```
ogr.geom_type('POINT')
  File "/usr/local/lib/python3.7/site-packages/gdaltools/ogr2ogrcmd.py", line 133, in geom_type
    if self.out_file_type=="PostgreSQL" and not self._geom_type:
AttributeError: 'Ogr2ogr' object has no attribute 'out_file_type'
```

**Comment by dispiste** [comment] 2019-02-08 14:03
Hi Josh, I've tested your initial code and I could successfully export the geojson as POINT type to PostGRES. The only difference is that I had to wrap your JSON with curly braces {}, like this:
```
{
   "geometry": {
      "type": "Point",
      "coordinates": [
         -1.0600739160455448,
         51.53592123798526
      ]
   }
}
```

So I don't know why you are getting the multipoint layer. Maybe it is caused by some differences on ogr and/or postgis versions, but I have no clue.

Regarding geom_type method, I've detected a bug which will be fixed.

**Comment by jpc2350** [comment] 2019-02-08 14:15
So I was calling the wrong part of the function anyway - ogr.geom_type = 'POINT' works rather than ogr.geom_type('POINT').

But it now works, and the geometry is being correctly typed as a point. Interesting that you can get it to work without needing that extra piece.

Hmm, I'll have another look.

**Comment by dispiste** [comment] 2019-02-08 14:29
You are right, there is no bug in geom_type. As you pointed, it is a setter so it must be used as an assignment:
`ogr.geom_type = 'POINT'`

I am closing the ticket now, but I'd be happy to learn why it is generating a MULTIPOINT in your environment, if you discover the cause. Note that this is only a wrapper on ogr2ogr command and you can see the actual command that has just been executed by using:
`print '"'+'" "'.join(ogr.args)+'"'`

**Closed as completed by dispiste** 2019-02-08 14:29 UTC
